:state: Needed
:date: 2021-05-07
:labels: design,

Terms and Definitions
=====================

For coherence across developers, we use a set of consistent
terms and definitions throughout Hypatia.  This is the
repository of such terms.

Hypervisor::
The combination of kernel and userspace components that permit
execution of a virtual machine on hardware.

Hyperkernel::
The bare-metal kernel that runs directly on the host.  It owns
and allocates the hardware, and provides services to virtual
machines.

Virtual Machine Monitor (VMM)::
The userspace portion of the hypervisor.  Note that in Hypatia,
this typically runs in the root VM.

Virtual Machine (VM)::
An instance of a virtual machine that runs under the hypervisor.

Root VM::
A specially privileged virtual machine, designed to run the
control plane and VMM for guest VMs.

Guest VM::
A VM that provides general service on behalf of a customer; it
is not especially privileged and not involved in running the
system.

Customer VM::
Another term for Guest VM.

Control plane::
The control software that directs the hypervisor and manages
resource allocation, runs device drivers, etc.

Driver VM::
A special class of VM provided to run a device driver and
provide services to the hypervisor, but does not provide general
computation.

Segment::
A segment is a region of shared virtual memory that contains
code and data that provide some useful function to the rest of
the system.  Inter-segment linkage is performed by means of
transfer vectors.

Task::
A unit of organization in the hypervisor.  Tasks are roughly
analogous to threads, but live in individual address spaces.  In
that sense, they are similar to processes, but are cooperatively
scheduled.  There is a limited, highly controlled, taxonomy of
tasks: VCPUs, VM control tasks and the system task.  Note that
tasks can be grouped into Task Sets.

Task Set::
An organizational grouping of tasks.  Each task set consists of
one or more tasks and exactly one leader.  A task set logically
groups related tasks, and members can view parts of the leader's
address space.  The canonical example is a virtual machine: a
"VM" is a task set consisting of the control task and VCPU
tasks.

Transfer Vector::
A transfer vector is a jump table at some well-known location
relative to the start of a segment.  That is, it is a table
indexed by a function identifier that points to executable code
within a segment.  One may think of it as an array of function
pointers.  Transfer vectors allow for inter-segment linkage and
function calls into the segment from e.g. tasks or other
segments.  These are deliberately chosen, as opposed to other,
more traditional forms of linkage, to keep the interfaces
exposed by segments small and decoupled.
